---
title: "Activity 12: Blue-Blocs"
subtitle: "Enhancing Computational Thinking through Interactive Coding Challenges."
grades: 4th, 5th, and 6th grade
time_required: "Varies by grade"
toc: true
---

## Description

Students will use the Blue-Bot robots to play with the Blue-Bloc app. The activity incorperates the use of blocking coding, a ataic used to simply the understading of code for students. The activity will also include the use of conditional statements that require new ays of thinking and improve skills in computational thinking.

## Time Required

- **Time Required**: 4th grade: 35min, 5th & 6th: 30min

## Materials Required

- Blue-Bot
- Blue-Bot Map
- Flashcards
- IPAD
- Pencil  
- Paper

### Step 1: Forming Groups

- Put students in groups of two at each Map, giving them each three rows of space to put down blank flashcards for obstacles and one picture flashcard as their goal.

- Each student needs a paper, pencil and IPAD to connect to their Blue-Bot

### Step 2: Creating Routes

- Encourage students to play around with Bee Bot to see the different blocks available to them for 5 minutes max.

- Using the flashcards and three rows avaliable to them, tell students to create routes they can run their Blue-Bots through. Give students up to 10 minutes to complete this

### Step 3: Creating Conditions

- With the paper and pencil tell students to create two restictions based upon the avaiable blocks on Blue-Blocs, they cannot have the same restrictions as their partner on the map
  - Examples: No forward block, No turning 45 degrees, Only 45 degree blocks for turns, Can only turn left etc...

### Step 4: Completing Routes and Switching

- Have the students run through their own routes with conditions and once completed, switch with their partner and abide by their restrictions.

- Once both students have done each other routes wait for another group to be done so they can switch places.

- Have the students keep their paper at their original map and use the new ones they find when switching

- Keep the students switching until they have done all the diffrent routes avaliable.

## Reflection

- Leave at least 5 minutes of the activity to ask questions about what they did

- Explore with students how easy or hard they found the activity

- Ask the students what they found were the hardest conditions to abide by.

- Ask them if there were any conditions they tried making but weren't able to.

## Summary

- Participation in the activity is meant to improve students computational thinking. Block coding helps students get a better understanding of how coding works and can help them improve their skills in programming. Encouraging students to create and solve obstacles for block coding will greatly improve their coding skills.
