---
title: "Activity 21: Shapes and A-to-B Movements with Blue-Bots"
subtitle: "Use the Blue-Bot to create squares and various A-to-B pathways, making sure to test different combinations of movements."
grades: 1st, 2nd
time_required: "30 minutes"
categories: ["Grade: Grade: 1", "Grade: 2", "Time: 30 Minutes"]
toc: true
page-layout: full
---

## Description

In this activity, students will use Blue-Bots to create squares made up of forward movements and left or right turns. After students progress through the sqaure challenge, they will attempt more complex challenges of driving the BlueBot from one point to another starting from various points. This approach fosters critical thinking and problem-solving skills while enhancing their understanding of the relationship between input and output in programming.

## Time Required

- **Time Required**: 30 minutes

## Materials Required

- Blue-Bots 
- Blue-Bot App: Blue's Bloc (IPAD)
- Blue-Bots Map
- Square Challenge Paper Instructions

### Step 1: Setting Up a Grid Map

- Each map should have at least two students, an ipad, a Blue Bot, and two copies of the paper instructions.
- Ensure there is one Blue-Bot for every Blue Bots map. If there are more students than available maps or Blue-Bots, pairing them is the best option.
    - When pairing students, ensure they take equal turns using the device.
- Use the ipad to generate random A-to-B pathways for the students to drive the Blue Bot through and place the bot on the starting place shown on the app.

### Step 2: Explaining the Conditional Sheet

- Students should be familiar with the Blue-Bots application, which uses code blocks or buttons to control movement. To refresh their awareness and with the help of the instruction paper, have them attempt to move the Blue Bot in two square rotations. Make one with only forward and left movements, and one with only forward and right movements.
- Once the sqaure challenge has been completed, set up the map to resemble the A-to-B generated by the ipad. Have the students use the ipad directions to traverse the bot using different direction cobinations.

### Step 3: Completing the Map 

- Encourage students to complete the course independently and assist those who are confused or struggling with the task.
- If students are hesitant to help, involve a nearby teacher to better manage the situation.
- Once a student finishes their pathway, have them reposition the Blue Bot as designated by the ipad's new pathway.
- After meeting their marked goals twice, allow them to modify the A-to-B pathways and provide guidance if their courses are not conditionally possible. 
- Once modifying their courses, ask them to keep track of how many times they meet their goal. 

## Reflection

At the end of the activity, gather the students and ask how many of them were able to create their squares and where, if applicable, they had any troubles. Additionally, for those who kept count, ask how many times they were able to complete their pathways.
    - What directional combinations were tricky and why?
    - Were there any pathways you found to be easy?
    - How many times were you able to finish your A-to-B pathways?

## Summary

By programming Blue-Bots to navigate maps with specific constraints, students develop an understanding of how conditions affect movement and decision-making. The activity reinforces computational thinking, logical reasoning, and teamwork while encouraging students to experiment with different coding sequences.
