---
title: "Activity 14: Code with Anna and Elsa"
subtitle: "Enhancing Computational Thinking through Interactive Coding Challenges."
grades: All grades
time_required: "30 minutes"
categories: ["Kindergarten", "1st Grade", "2nd Grade", "3rd Grade", "4th Grade", "5th Grade", "6th Grade", "30 Minutes"]
toc: true
---

## Description

Students will engage with the Code.org platform to play an interactive coding game inspired by the movie "Frozen." Through this activity, they will utilize block-based coding to deepen their comprehension of fundamental programming concepts. As they progress through the game, students will learn how to construct sequences, loops, and conditional statements, and observe how these elements interact to produce the desired outcomes. This hands-on experience aims to enhance their understanding of how coding works in a fun and educational environment, fostering their problem-solving skills and creativity

## Materials required

- IPAD 
- Code.org platform: [Code with Anna and Elsa](https://studio.code.org/s/frozen) 

## Steps to conduct the activity

### Step 1: Setup and Introduction

- Open the Code.org platform on iPads.
- Show students the introductory video provided before starting the activity.

### Step 2: Engaging with Minecraft Blocks

- Guide students through the initial stages of the Frozen block coding game.
- Disable subsequent instructional videos to encourage independent exploration.

## Reflection

- Pause at the 30-minute mark to discuss progress and challenges.
- Ask students to describe what they observed Minecraft mobs doing with the block codes.
- Relate the activity to game development, emphasizing how coding principles translate into interactive gameplay experiences.

## Learning Outcomes

- By introducing them to basic coding principles, students will develop a stronger grasp of programming, leading to improved comprehension when they encounter more complex coding tasks in the future. This early exposure aims to build their confidence and proficiency in understanding and applying code effectively.