---
title: "Activity 8: Designing and Programming Robots"
subtitle: "Encouraging creativity and critical thinking through robot design and online coding."
grades: Kindergarden - 5th grade
time_required: "30 minutes"
keywords: ["kindergarten", "1st", "2nd", "3rd", "4th", "5th", "30 minutes"]
toc: true
---

## Objective

This activity aims to encourage students to reflect on their experiences with robots, foster creativity through drawing, and develop critical thinking skills through an engaging online coding exercise.

## Materials Needed

- Paper and pencils for drawing
- Computers or tablets with internet access for the online activity

## Instructions

### Step 1: Reflection and Observation

- Provide each student with a piece of paper.
- Ask students to reflect on their experiences with robots, especially what they observed during their time at the camp. This includes features like distance sensors, speakers, and cameras.
- Encourage them to list as many features and details as they can remember.

### Step 2: Creative Drawing

- Based on their reflections, instruct students to draw their own robot.
- This drawing session allows students to express their creativity and apply what they have learned about the various parts and functions of robots.

### Step 3: Online Coding Activity - RodoCode

- After the drawing session, introduce students to the online activity called RodoCode on Code.org.
- RodoCode is an interactive coding exercise where students use blocks to program a robot to reach its destination.
- Emphasize that this activity will enhance critical thinking and problem-solving skills while reinforcing their understanding of robotics concepts.

## Summary

This activity engages students in reflecting on their robot experiences, expressing creativity through drawing, and developing coding skills through an online exercise. It combines observation, artistic expression, and computational thinking in a fun and educational manner.
